site_name: Demo Seite von Pierr&#233
site_url:
http://gbs.niederer.swiss/dta22/Pierre
theme:
  name: material
  pallette:
    scheme: slate
    primary: deep purple
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
nav:
  - Home: index.md
  - Details: details.md
copyright: 'Version: ${BUILD_VERSION}'
